version : '3.4'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    networks:
      - test_network
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - test_network
  project:
    image: rlagusdnr120/my-todo-project
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    networks:
      - test_network
    depends_on:
      - redis
      - mysql

networks:
  test_network:

