version : '3.4'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  redis:
    image: redis
    ports:
      - 6379:6379
  project:
    image: rlagusdnr120/my-todo-project
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      - redis
      - mysql

